name: Build the LaTeX template

on:
  push:
    branches:
      - main
  pull_request:

env:
  VERSION_FILE: NOVAthesisFiles/nt-version.sty
  ROW_VERSION: 1
  START_POS_VERSION: 33
  EMAIL_GITHUB: joao.lourenco@fct.unl.pt
  USERNAME_GITHUB: joaomlourenco

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Compile the LaTex template
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: bash .Build/build.sh
      - name: Upload the template PDF file
        uses: actions/upload-artifact@v3
        with:
          name: Template
          path: template.pdf
      - name: Push changes to the repository
        run: |
          git config --global user.email "$EMAIL_GITHUB"
          git config --global user.name "$USERNAME_GITHUB"
          row=$(head -n$ROW_VERSION $VERSION_FILE)
          version="${row:$START_POS_VERSION:-1}"
          git add -f template.pdf
          git commit -m "Version $version"
          git push