name: Build the LaTeX template

on:
  push:
    branches:
      - main
  pull_request:

env:
  VERSION_FILE: NOVAthesisFiles/nt-version.sty
  ROW_VERSION: 1
  START_POS_VERSION: 33
  EMAIL_GITHUB: joao.lourenco@fct.unl.pt
  USERNAME_GITHUB: joaomlourenco

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install LaTeX
        run: sudo apt install texlive -y
      - name: Install Latexmk
        run: sudo apt-get install -y latexmk
      - name: Compile the LaTeX template
        run: bash ./build.sh
      - name: Upload the PDF template file
        uses: actions/upload-artifact@v3
        with:
          name: Log
          path: template.log
